name: Windows

on:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "README.md"
      - "LICENSE"

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        qt_ver: [6.8.0]
        qt_target: [desktop]
        qt_arch: [win64_mingw]
        include:
          - qt_arch: win64_mingw
            msvc_arch: x86

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install aqtinstall
        run: pip install aqtinstall

      - name: Install Qt 6.8.0 (MinGW)
        shell: bash
        run: |
          python -m aqt install-qt windows desktop 6.8.0 ${{ matrix.qt_arch }} \
            --timeout 120 \
            --base https://mirrors.dotsrc.org/qtproject \
            --external "C:\Program Files\7-Zip\7z.exe"

      - name: Set up MinGW environment
        shell: cmd
        run: |
          set PATH=C:\mingw-w64\bin;%PATH%
          set QMAKESPEC=win32-g++-mingw
          set QMAKE_CXXFLAGS=-static
          set QMAKE_LFLAGS=-static

      - name: Build with qmake + mingw32-make
        shell: cmd
        run: |
          qmake
          mingw32-make
