name: Windows

on:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "README.md"
      - "LICENSE"

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        qt_arch: [win64_msvc2019_64]
        include:
          - qt_arch: win64_msvc2019_64
            msvc_arch: x64

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install aqtinstall
        run: pip install aqtinstall

      - name: List available Qt architectures
        run: python -m aqt list-qt windows desktop --arch 6.8.0

      - name: Install Qt 6.8.0 (64-bit)
        shell: bash
        run: |
          python -m aqt install-qt windows desktop 6.8.0 ${{ matrix.qt_arch }} \
            --timeout 120 \
            --base https://mirrors.dotsrc.org/qtproject \
            --external "C:\Program Files\7-Zip\7z.exe"

      - name: Set up MSVC environment (64-bit)
        shell: cmd
        run: |
          for /f "usebackq tokens=*" %%i in (`vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -find **\vcvarsall.bat`) do set VCVARSALL=%%i
          call "%VCVARSALL%" ${{ matrix.msvc_arch }}

      - name: Build with qmake + nmake
        shell: cmd
        run: |
          qmake
          nmake
