name: Windows

on:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "README.md"
      - "LICENSE"

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        qt_ver: [6.9.1] # 只选择 Qt 6.9.1
        qt_target: [desktop]
        qt_arch: [win64_msvc2019_64, win32_msvc2019] # 仍然保留 msvc2019 架构
        exclude:
          - qt_ver: 5.9.8
            qt_arch: win32_msvc2019
        include:
          - qt_arch: win64_msvc2019_64
            msvc_arch: x64
          - qt_arch: win32_msvc2019
            msvc_arch: x86

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_ver }}
          target: ${{ matrix.qt_target }}
          arch: ${{ matrix.qt_arch }}

      - name: Set up MSVC environment
        shell: cmd
        run: |
          echo "Finding vcvarsall..."
          for /f "usebackq tokens=*" %%i in (`vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -find **\vcvarsall.bat`) do set VCVARSALL=%%i
          echo "Using vcvarsall at %VCVARSALL%"
          call "%VCVARSALL%" ${{ matrix.msvc_arch }}

      - name: Build with qmake + nmake
        shell: cmd
        run: |
          qmake
          nmake
