name: Windows Static Qt Build

on:
  push: { paths-ignore: ["README.md", "LICENSE"] }
  pull_request: { paths-ignore: ["README.md", "LICENSE"] }

jobs:
  static-qt:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          choco install ninja cmake
          choco install visualstudio2022buildtools --includeRecommended --quiet

      - name: Download Qt Sources
        run: |
          # 用 aqtinstall 下载源代码（假设源可用）
          pip install aqtinstall
          aqt list-qt windows desktop --arch 6.9.1
          aqt install-qt windows desktop 6.9.1 win64_msvc2019_64 -m src --outputdir qt_src

      - name: Build static Qt (x64)
        shell: cmd
        run: |
          cd qt_src/6.9.1/win64_msvc2019_64/Src
          mkdir build-static && cd build-static
          cmake .. ^
            -A x64 ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DQT_BUILD_SHARED=OFF ^
            -DQT_FEATURE_static=ON ^
            -DCMAKE_INSTALL_PREFIX=%CD%\../install ^
            -DSKIP=qtwebengine ^
            -DENABLE_TESTS=OFF
          cmake --build . --parallel 4
          cmake --install .

      - name: Build your project using static Qt
        shell: cmd
        run: |
          set QT_STATIC_DIR=%CD%\qt_src\6.9.1\win64_msvc2019_64\install
          set PATH=%QT_STATIC_DIR%\bin;%PATH%
          cd your_project
          qmake -static -spec win32-msvc2019
          nmake
